global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: booking_service
    static_configs:
      - targets: ["booking_service:8000"]

  - job_name: car_service
    static_configs:
      - targets: ["car_service:8000"]

  - job_name: fines_service
    static_configs:
      - targets: ["fines_service:8000"]

  - job_name: geo_service
    static_configs:
      - targets: ["geo_service:8000"]

  - job_name: promo_service
    static_configs:
      - targets: ["promo_service:8000"]

  - job_name: support_service
    static_configs:
      - targets: ["support_service:8000"]

  - job_name: trip_service
    static_configs:
      - targets: ["trip_service:8000"]

  - job_name: user_service
    static_configs:
      - targets: ["user_service:8000"]

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
